2024 11 04 fix ara bauwerk export
QGEP/qgepqwat2ili pull request #178
Opened 2024-11-04 16:39 UTC by sjib

2024-11-04 16:39 UTC, sjib commented
Should solve https://github.com/QGEP/qgepqwat2ili/issues/177

2024-11-04 16:44 UTC, sjib commented
Relation to Abwasserbauwerk is now empty with SIA405 Export:

![grafik](https://github.com/user-attachments/assets/82aadb2f-9b4e-444a-89f6-cd765cb92f2a)

Abwasserknoten is still exported.
@urskaufmann Is that what you expect?

Maybe in future ARABauwerk should become part of SIA405 Abwasser.
Do we have to implement the same for the other subclasses that are not part of SIA405 Abwasser (Abflusslose_Toilette and KLARA?)
![grafik](https://github.com/user-attachments/assets/27187a59-8b5f-4fa2-ab65-d207303c1bb8)

2024-11-04 16:49 UTC, sjib commented
For tww this would have to be extended:

```
    # select all obj_id from wastewater_structure that are not in wwtp_structure
    cursor.execute(
        "SELECT * FROM qgep_od.wastewater_structure WHERE obj_id NOT IN (SELECT obj_id FROM qgep_od.wwtp_structure);"
    )
```

2024-11-04 17:05 UTC, sjib commented
https://github.com/QGEP/qgepqwat2ili/blob/7372cb27e5cfaa7ec6b5f78f3f756666d7589243/qgepqwat2ili/utils/ili2db.py#L465C10-L465C117

2024-11-04 20:57 UTC, urskaufmann commented
_Abwasserknoten is still exported._

I do not expect, that the node is exported. First of all, I expect that there is no error, when I should export such a database to SIA405. 
I think, that wastewater_networkelements without relation to a wastewater_structure should be really exceptions. And VSA / SIA should answer these questions and make changes, if necessary. 
I think the same problem will/can occur in model 2020 with e.g. Spuelstutzen or other structure parts, if TWW does not handle this problems.

2024-11-04 20:59 UTC, urskaufmann commented
I have no checked with this new code. And I got the next error (sorry): no more abwassernetzelement, but bauwerksteil:



              File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 771, in _commit_impl
              self.engine.dialect.do_commit(self.connection)
              File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\default.py", line 561, in do_commit
              dbapi_connection.commit()
             psycopg2.errors.ForeignKeyViolation: insert or update on table "bauwerksteil" violates foreign key constraint "bauwerksteil_abwasserbauwerkref_fkey"
             DETAIL: Key (abwasserbauwerkref)=(1108) is not present in table "abwasserbauwerk".
             
             
             The above exception was the direct cause of the following exception:
             
             Traceback (most recent call last):
              File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 715, in action_do_export
              qgepsia405_export(
              File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep161_prerealise/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\qgepsia405\export.py", line 1196, in qgep_export
              abwasser_session.commit()
              File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 1046, in commit
              self.transaction.commit()
              File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 508, in commit
              t[1].commit()
              File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1762, in commit
              self._do_commit()
              File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1793, in _do_commit
              self.connection._commit_impl()
              File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 773, in _commit_impl
              self._handle_dbapi_exception(e, None, None, None, None)
              File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
              util.raise_(
              File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
              raise exception
              File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 771, in _commit_impl
              self.engine.dialect.do_commit(self.connection)
              File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\default.py", line 561, in do_commit
              dbapi_connection.commit()
             sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "bauwerksteil" violates foreign key constraint "bauwerksteil_abwasserbauwerkref_fkey"
             DETAIL: Key (abwasserbauwerkref)=(1108) is not present in table "abwasserbauwerk".
             
             (Background on this error at: http://sqlalche.me/e/13/gkpj)

2024-11-04 21:00 UTC, urskaufmann commented
I did then delete the cover, that was with this ARA-Bauwerk, and then it works....

2024-11-04 21:02 UTC, urskaufmann requested changes
Does not work, if the ARA-Bauwerk has a structure_part. All Structure_Parts of Wastewater_structures, that are not in the export, can also not be in the export

2024-11-05 09:33 UTC, sjib commented
Thanks for the hint - then I have to adapt this also.

Looks a little bit trickier to not export the cover. First work around would be to just leave the fk_abwasserbauerk empty also for Deckel, etc.

2024-11-12 19:39 UTC, sjib commented
```
AttributeError: 'list' object has no attribute 'add' 
Traceback (most recent call last):
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testingdev165/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 715, in action_do_export
    qgepsia405_export(
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testingdev165/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\qgepsia405\export.py", line 67, in qgep_export
    subset_ids = add_to_selection(subset_ids, get_ws_wn_ids("wastewater_structure"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testingdev165/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\utils\ili2db.py", line 583, in add_to_selection
    selected_ids = selected_ids.add(list_item)
                   ^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'add'
```

replace with append

2024-11-12 19:57 UTC, sjib commented
```
2024-11-12T20:45:02     WARNING    Traceback (most recent call last):
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testingdev165/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 715, in action_do_export
              qgepsia405_export(
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testingdev165/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\qgepsia405\export.py", line 717, in qgep_export
              query = query.join(QGEP.wastewater_structure, QGEP.wastewater_networkelement).filter(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "", line 2, in join
              File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\base.py", line 279, in _generative
              x = fn(self, *args, **kw)
              ^^^^^^^^^^^^^^^^^^^^^
              File "", line 2, in join
              File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\base.py", line 306, in generate
              fn(self, *args, **kw)
              File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\query.py", line 2429, in join
              onclause_element = coercions.expect(
              ^^^^^^^^^^^^^^^^^
              File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\coercions.py", line 395, in expect
              resolved = impl._literal_coercion(
              ^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\coercions.py", line 909, in _literal_coercion
              self._raise_for_expected(element)
              File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\coercions.py", line 518, in _raise_for_expected
              raise exc.ArgumentError(msg, code=code) from err
             sqlalchemy.exc.ArgumentError: ON clause, typically a SQL expression or ORM relationship attribute expected, got .
```

2024-11-15 10:32 UTC, sjib commented
Filter     query = qgep_session.query(QGEP.dryweather_downspout)

```
Ein Fehler trat bei der Ausführung von Python-Code auf: 

sqlalchemy.exc.ArgumentError: ON clause, typically a SQL expression or ORM relationship attribute expected, got . 
Traceback (most recent call last):
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testingdev165/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 715, in action_do_export
    qgepsia405_export(
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testingdev165/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\qgepsia405\export.py", line 717, in qgep_export
    query = query.join(QGEP.wastewater_structure, QGEP.wastewater_networkelement).filter(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 2, in join
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\base.py", line 279, in _generative
    x = fn(self, *args, **kw)
        ^^^^^^^^^^^^^^^^^^^^^
  File "", line 2, in join
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\base.py", line 306, in generate
    fn(self, *args, **kw)
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\query.py", line 2429, in join
    onclause_element = coercions.expect(
                       ^^^^^^^^^^^^^^^^^
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\coercions.py", line 395, in expect
    resolved = impl._literal_coercion(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\coercions.py", line 909, in _literal_coercion
    self._raise_for_expected(element)
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\coercions.py", line 518, in _raise_for_expected
    raise exc.ArgumentError(msg, code=code) from err
sqlalchemy.exc.ArgumentError: ON clause, typically a SQL expression or ORM relationship attribute expected, got .


Python-Version: 3.12.4 (main, Jun 10 2024, 12:48:35) [MSC v.1938 64 bit (AMD64)] 
QGIS-Version: 3.34.8-Prizren Prizren, 91642333 
```

2024-11-15 10:48 UTC, sjib commented
```
NameError: name 'dryweather_downspout' is not defined 
Traceback (most recent call last):
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testingdev165/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 715, in action_do_export
    qgepsia405_export(
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testingdev165/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\qgepsia405\export.py", line 720, in qgep_export
    query = query.join(QGEP.wastewater_structure,dryweather_downspout.fk_wastewater_structure == wastewater_structure.obj_id).join(QGEP.wastewater_networkelement).filter(
                                                 ^^^^^^^^^^^^^^^^^^^^
NameError: name 'dryweather_downspout' is not defined
```

2024-11-15 12:34 UTC, sjib commented
https://docs.sqlalchemy.org/en/20/orm/queryguide/select.html#joins-to-a-target-entity

2024-11-15 12:36 UTC, sjib commented
- [ ] adapt filter queries for other subclasses of structure_part

2024-11-15 13:25 UTC, sjib commented
- [ ] to do adapt in qgep also
- [ ] to do adapte in qgepdss for selection also

2024-11-15 16:48 UTC, sjib commented
adapted filters

- [ ] meachnische_vorreinigung

2024-11-15 16:56 UTC, sjib commented
@urskaufmann Can you try again?

2024-11-15 20:11 UTC, urskaufmann commented
Export SIA405 no selection: no error. Does not export 3 nodes, that are not connected to a wastewater_structure, does not export a channel, that was not connected from a wastewater_structure.
Export DSS no selection: no error. Seems to be ok



****************************************************
Export DSS, a selction of reaches: I get this error:

Ein Fehler trat bei der Ausführung von Python-Code auf: 

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) missing FROM-clause entry for table "structure_part" LINE 2: ...pretreatment JOIN qgep_od.wastewater_structure ON qgep_od.st...                                                             ^ [SQL: SELECT qgep_od.mechanical_pretreatment.obj_id AS qgep_od_mechanical_pretreatment_obj_id, qgep_od.mechanical_pretreatment.identifier AS qgep_od_mechanical_pretreatment_identifier, qgep_od.mechanical_pretreatment.kind AS qgep_od_mechanical_pretreatment_kind, qgep_od.mechanical_pretreatment.remark AS qgep_od_mechanical_pretreatment_remark, qgep_od.mechanical_pretreatment.last_modification AS qgep_od_mechanical_pretreatment_last_modification, qgep_od.mechanical_pretreatment.fk_dataowner AS qgep_od_mechanical_pretreatment_fk_dataowner, qgep_od.mechanical_pretreatment.fk_provider AS qgep_od_mechanical_pretreatment_fk_provider, qgep_od.mechanical_pretreatment.fk_infiltration_installation AS qgep_od_mechanical_pretreatment_fk_infiltration_installat_1, qgep_od.mechanical_pretreatment.fk_wastewater_structure AS qgep_od_mechanical_pretreatment_fk_wastewater_structure FROM qgep_od.mechanical_pretreatment JOIN qgep_od.wastewater_structure ON qgep_od.structure_part.fk_wastewater_structure = qgep_od.wastewater_structure.obj_id JOIN qgep_od.wastewater_networkelement ON qgep_od.wastewater_structure.obj_id = qgep_od.wastewater_networkelement.fk_wastewater_structure WHERE qgep_od.wastewater_networkelement.obj_id IN (%(obj_id_1)s, %(obj_id_2)s, .......

Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: missing FROM-clause entry for table "structure_part"
LINE 2: ...pretreatment JOIN qgep_od.wastewater_structure ON qgep_od.st...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep164/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 724, in action_do_export
    qgepdss_export(
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\qgep164/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\qgepdss\export.py", line 2190, in qgep_export
    for row in query:
               ^^^^^
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\orm\query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\orm\query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) missing FROM-clause entry for table "structure_part"
LINE 2: ...pretreatment JOIN qgep_od.wastewater_structure ON qgep_od.st...
                                                             ^

[SQL: SELECT qgep_od.mechanical_pretreatment.obj_id AS qgep_od_mechanical_pretreatment_obj_id, qgep_od.mechanical_pretreatment.identifier AS qgep_od_mechanical_pretreatment_identifier, qgep_od.mechanical_pretreatment.kind AS qgep_od_mechanical_pretreatment_kind, qgep_od.mechanical_pretreatment.remark AS qgep_od_mechanical_pretreatment_remark, qgep_od.mechanical_pretreatment.last_modification AS qgep_od_mechanical_pretreatment_last_modification, qgep_od.mechanical_pretreatment.fk_dataowner AS qgep_od_mechanical_pretreatment_fk_dataowner, qgep_od.mechanical_pretreatment.fk_provider AS qgep_od_mechanical_pretreatment_fk_provider, qgep_od.mechanical_pretreatment.fk_infiltration_installation AS qgep_od_mechanical_pretreatment_fk_infiltration_installat_1, qgep_od.mechanical_pretreatment.fk_wastewater_structure AS qgep_od_mechanical_pretreatment_fk_wastewater_structure 
FROM qgep_od.mechanical_pretreatment JOIN qgep_od.wastewater_structure ON qgep_od.structure_part.fk_wastewater_structure = qgep_od.wastewater_structure.obj_id JOIN qgep_od.wastewater_networkelement ON qgep_od.wastewater_structure.obj_id = qgep_od.wastewater_networkelement.fk_wastewater_structure 
WHERE qgep_od.wastewater_networkelement.obj_id IN (%(obj_id_1)s, %(obj_id_2)s, %(obj_id_3)s, %(obj_id_4)s, %(obj_id_5)s, %(obj_id_6)s, %(obj_id_7)s, %(obj_id_8)s, %(obj_id_9)s, %(obj_id_10)s, %(obj_id_11)s, %(obj_id_12)s, %(obj_id_13)s, %(obj_id_14)s, %(obj_id_15)s, %(obj_id_16)s, %(obj_id_17)s, %(obj_id_18)s, %(obj_id_19)s, %(obj_id_20)s, %(obj_id_21)s, %(obj_id_22)s, %(obj_id_23)s, %(obj_id_24)s, %(obj_id_25)s, %(obj_id_26)s, %(obj_id_27)s, %(obj_id_28)s, %(obj_id_29)s, %(obj_id_30)s, %(obj_id_31)s, %(obj_id_32)s, %(obj_id_33)s, %(obj_id_34)s, %(obj_id_35)s, %(obj_id_36)s, %(obj_id_37)s, %(obj_id_38)s, %(obj_id_39)s, %(obj_id_40)s, %(obj_id_41)s, %(obj_id_42)s, %(obj_id_43)s, %(obj_id_44)s, %(obj_id_45)s, %(obj_id_46)s, %(obj_id_47)s, %(obj_id_48)s, %(obj_id_49)s, %(obj_id_50)s, %(obj_id_51)s, %(obj_id_52)s, %(obj_id_53)s, %(obj_id_54)s, %(obj_id_55)s, %(obj_id_56)s, %(obj_id_57)s, %(obj_id_58)s, %(obj_id_59)s, %(obj_id_60)s, %(obj_id_61)s, %(obj_id_62)s, %(obj_id_63)s, %(obj_id_64)s, %(obj_id_65)s, %(obj_id_66)s, %(obj_id_67)s, %(obj_id_68)s, %(obj_id_69)s, %(obj_id_70)s, %(obj_id_71)s, %(obj_id_72)s, %(obj_id_73)s, %(obj_id_74)s, %(obj_id_75)s, %(obj_id_76)s, %(obj_id_77)s, %(obj_id_78)s, %(obj_id_79)s, %(obj_id_80)s, %(obj_id_81)s, %(obj_id_82)s, %(obj_id_83)s, %(obj_id_84)s, %(obj_id_85)s, %(obj_id_86)s, %(obj_id_87)s, %(obj_id_88)s, %(obj_id_89)s, %(obj_id_90)s, %(obj_id_91)s, %(obj_id_92)s, %(obj_id_93)s, %(obj_id_94)s, %(obj_id_95)s, %(obj_id_96)s, %(obj_id_97)s, %(obj_id_98)s, %(obj_id_99)s, %(obj_id_100)s, %(obj_id_101)s, %(obj_id_102)s, %(obj_id_103)s, %(obj_id_104)s, %(obj_id_105)s, %(obj_id_106)s, %(obj_id_107)s, %(obj_id_108)s, %(obj_id_109)s, %(obj_id_110)s, %(obj_id_111)s, %(obj_id_112)s, %(obj_id_113)s, % [...]

2024-11-19 16:09 UTC, urskaufmann commented
Till now I have no mech Vorreinigung...

2024-11-19 16:20 UTC, sjib commented
export selection dss
```
sqlalchemy.exc.ArgumentError: ON clause, typically a SQL expression or ORM relationship attribute expected, got . 
Traceback (most recent call last):
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testingdev165/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 724, in action_do_export
    qgepdss_export(
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\testingdev165/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\qgepdss\export.py", line 2229, in qgep_export
    query = query.join(QGEP.infiltration_installation, QGEP.wastewater_networkelement).filter(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 2, in join
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\base.py", line 279, in _generative
    x = fn(self, *args, **kw)
        ^^^^^^^^^^^^^^^^^^^^^
  File "", line 2, in join
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\base.py", line 306, in generate
    fn(self, *args, **kw)
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\query.py", line 2429, in join
    onclause_element = coercions.expect(
                       ^^^^^^^^^^^^^^^^^
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\coercions.py", line 395, in expect
    resolved = impl._literal_coercion(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\coercions.py", line 909, in _literal_coercion
    self._raise_for_expected(element)
  File "C:\Users\Stefan\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\coercions.py", line 518, in _raise_for_expected
    raise exc.ArgumentError(msg, code=code) from err
sqlalchemy.exc.ArgumentError: ON clause, typically a SQL expression or ORM relationship attribute expected, got .


Python-Version: 3.12.4 (main, Jun 10 2024, 12:48:35) [MSC v.1938 64 bit (AMD64)] 
QGIS-Version: 3.34.8-Prizren Prizren, 91642333 
```

2024-11-19 20:49 UTC, sjib commented
- [ ] check if ws have to be added also in dss export if selection
- [ ] check missing data - comments urs

2024-12-20 14:22 UTC, closed without merging